name: snowflake_raw_import_vatsim_gcp_deployment
on:
  push:
    branches:
      - 'main'
    paths:
      - 'scheduled_jobs/gcp/snowflake/functions/raw_import_vatsim/**'
  pull_request:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cloud Functions Deploy
        uses: google-github-actions/deploy-cloud-functions@main
        with:
          name: snowflake-vatsim-raw
          runtime: python39
          region: europe-west1
          timeout: 60
          memory_mb: 256
          ingress_settings: ALLOW_ALL
          credentials: ${{ secrets.GCP_SA_KEY }}
          source_dir: ./scheduled_jobs/gcp/snowflake/functions/raw_import_vatsim/
          entry_point: postData
          env_vars: SNOWFLAKE_ACCOUNT=${{ secrets.SNOWFLAKE_ACCOUNT }},SNOWFLAKE_GCP_USER=${{ secrets.SNOWFLAKE_GCP_USER }},SNOWFLAKE_GCP_USER_PASSWORD=${{ secrets.SNOWFLAKE_GCP_USER_PASSWORD }}